bugfixes

diff --git a/mapreduce/Examples2/Mandelbrot-set/Mandelbrot-set_5/scripts/runtest2 b/mapreduce/Examples2/Mandelbrot-set/Mandelbrot-set_5/scripts/runtest2
--- a/mapreduce/Examples2/Mandelbrot-set/Mandelbrot-set_5/scripts/runtest2
+++ b/mapreduce/Examples2/Mandelbrot-set/Mandelbrot-set_5/scripts/runtest2
@@ -1,22 +1,26 @@
 #!/bin/bash
 
-[ -n "$MR_BIN" ] || { echo "Undefined variable: MR_BIN"; exit 1; }
-[ -n "$START_WORKER_SCRIPT" ] || { echo "Undefined variable: START_WORKER_SCRIPT"; exit 1; }
-[ -n "$CLIENT" ] || { echo "Undefined variable: CLIENT"; exit 1; }
-[ -n "$COPY_WORKER_DATA" ] || { echo "Undefined variable: COPY_WORKER_DATA"; exit 1; }
-[ -n "$1" ] || { echo "Parameter missing: WORKERS"; exit 1; }
-[ -n "$2" ] || { echo "Parameter missing: SPLITTERS"; exit 1; }
-[ -n "$3" ] || { echo "Parameter missing: MAPPERS"; exit 1; }
-[ -n "$4" ] || { echo "Parameter missing: REDUCERS"; exit 1; }
-[ -n "$5" ] || { echo "Parameter missing: FILENAME"; exit 1; }
-[ -n "$6" ] || { echo "Parameter missing: WORDS"; exit 1; }
+[ -n "$MR_BIN" ] || { echo "$0 Undefined variable: MR_BIN"; exit 1; }
+[ -n "$START_WORKER_SCRIPT" ] || { echo "$0 Undefined variable: START_WORKER_SCRIPT"; exit 1; }
+[ -n "$CLIENT" ] || { echo "$0 Undefined variable: CLIENT"; exit 1; }
+[ -n "$COPY_WORKER_DATA" ] || { echo "$0 Undefined variable: COPY_WORKER_DATA"; exit 1; }
+[ -n "$1" ] || { echo "$0 Parameter missing: WORKERS"; exit 1; }
+[ -n "$2" ] || { echo "$0 Parameter missing: SPLITTERS"; exit 1; }
+[ -n "$3" ] || { echo "$0 Parameter missing: MAPPERS"; exit 1; }
+[ -n "$4" ] || { echo "$0 Parameter missing: FILENAME"; exit 1; }
+[ -n "$5" ] || { echo "$0 Parameter missing: W"; exit 1; }
+[ -n "$6" ] || { echo "$0 Parameter missing: H"; exit 1; }
+[ -n "$7" ] || { echo "$0 Parameter missing: Z"; exit 1; }
+[ -n "$8" ] || { echo "$0 Parameter missing: IT"; exit 1; }
 
 WORKERS="$1"
 SPLITTERS="$2"
 MAPPERS="$3"
-REDUCERS="$4"
-FILENAME="$5"
-WORDS="$6"
+FILENAME="$4"
+W="$5"
+H="$6"
+Z="$7"
+IT="$8"
 
 echo "Doing run: $WORKERS / $SPLITTERS / $MAPPERS / $REDUCERS"
 # Start MR sytem and wait a sec
@@ -36,7 +40,7 @@ mkdir "data_$FILENAME_PREFIX" || { echo "dir exist do not overwrite it: exit"; e
 cd "data_$FILENAME_PREFIX"
 
 # run function
-/usr/bin/time -o "time.txt" -v "$CLIENT" "$FILENAME" "($SPLITTERS,$MAPPERS,$REDUCERS)" "$WORDS" +RTS -N3 -K4G -s"Memory.txt"
+/usr/bin/time -o "time.txt" -v "$CLIENT" "$FILENAME" "($W,$H,$Z,$IT)" "($SPLITTERS,$MAPPERS)" +RTS -N3 -K4G -s"Memory.txt"
 
 # stop workers
 $START_WORKER_SCRIPT stop 1 $WORKERS
diff --git a/mapreduce/Examples2/Mandelbrot-set/Mandelbrot-set_5/scripts/startstopworkers b/mapreduce/Examples2/Mandelbrot-set/Mandelbrot-set_5/scripts/startstopworkers
--- a/mapreduce/Examples2/Mandelbrot-set/Mandelbrot-set_5/scripts/startstopworkers
+++ b/mapreduce/Examples2/Mandelbrot-set/Mandelbrot-set_5/scripts/startstopworkers
@@ -1,31 +1,23 @@
 #!/bin/bash
 
-[ -n "$DOSSH" ] || { echo "Undefined variable: DOSSH"; exit 1; }
-[ -n "$WORKERS" ] || { echo "Undefined variable: WORKERS"; exit 1; }
-[ -n "$WORKER_DIR" ] || { echo "Undefined variable: WORKER_DIR"; exit 1; }
-[ -n "$WORKER_SSH_LOCATION" ] || { echo "Undefined variable: WORKER_SSH_LOCATION"; exit 1; }
-[ -n "$WORKER_BIN" ] || { echo "Undefined variable: WORKER_BIN"; exit 1; }
-[ -n "$WORKER_SH" ] || { echo "Undefined variable: WORKER_SH"; exit 1; }
-[ -n "$WORKER_PID" ] || { echo "Undefined variable: WORKER_PID"; exit 1; }
-[ -n "$1" ] || { echo "Parameter missing: OPT"; exit 1; }
-[ -n "$2" ] || { echo "Parameter missing: IP1"; exit 1; }
-[ -n "$3" ] || { echo "Parameter missing: IP2"; exit 1; }
+[ -n "$DOSSH" ] || { echo "$0 Undefined variable: DOSSH"; exit 1; }
+[ -n "$WORKER_DIR" ] || { echo "$0 Undefined variable: WORKER_DIR"; exit 1; }
+[ -n "$WORKER_SSH_LOCATION" ] || { echo "$0 Undefined variable: WORKER_SSH_LOCATION"; exit 1; }
+[ -n "$WORKER_BIN" ] || { echo "$0 Undefined variable: WORKER_BIN"; exit 1; }
+[ -n "$WORKER_SH" ] || { echo "$0 Undefined variable: WORKER_SH"; exit 1; }
+[ -n "$WORKER_PID" ] || { echo "$0 Undefined variable: WORKER_PID"; exit 1; }
+[ -n "$1" ] || { echo "$0 Parameter missing: OPT"; exit 1; }
+[ -n "$2" ] || { echo "$0 Parameter missing: IP1"; exit 1; }
+[ -n "$3" ] || { echo "$0 Parameter missing: IP2"; exit 1; }
 
 OPT="$1"
 shift
+
 case $OPT in
   start)
-  for I in $WORKERS
-  do
-    WORKER_DIR2="${WORKER_DIR}_${I}"
-    $DOSSH $1 $2 "rm $WORKER_DIR2 -rf && mkdir -p $WORKER_DIR2 && cd $WORKER_DIR2 && scp $WORKER_SSH_LOCATION/$WORKER_BIN .  &&  scp $WORKER_SSH_LOCATION/scripts/$WORKER_SH . && start-stop-daemon --start -p $WORKER_DIR2/$WORKER_PID --background --startas $WORKER_DIR2/$WORKER_SH $WORKER_DIR2 10000 $WORKER_PID"
-  done
+  $DOSSH $1 $2 "rm $WORKER_DIR -rf && mkdir -p $WORKER_DIR && cd $WORKER_DIR && scp $WORKER_SSH_LOCATION/$WORKER_BIN .  &&  scp $WORKER_SSH_LOCATION/scripts/$WORKER_SH . && start-stop-daemon --start -p $WORKER_DIR/$WORKER_PID --background --startas $WORKER_DIR/$WORKER_SH $WORKER_DIR 10000 $WORKER_PID"
   ;;
   stop)
-  for I in $WORKERS
-  do
-    WORKER_DIR2="${WORKER_DIR}_${I}"
-    $DOSSH $1 $2 "start-stop-daemon --stop --signal 2 -p $WORKER_DIR2/$WORKER_PID"
-  done
+  $DOSSH $1 $2 "start-stop-daemon --stop --signal 2 -p $WORKER_DIR/$WORKER_PID"
   ;; 
 esac
