yyy
darcs-hash:20100102114240-f5258-18bece29527e5a901b8d0955af43a51110750acc.gz

diff --git a/Examples2/Re/scripts/runtest2 b/Examples2/Re/scripts/runtest2
--- a/Examples2/Re/scripts/runtest2
+++ b/Examples2/Re/scripts/runtest2
@@ -9,8 +9,8 @@
 [ -n "$3" ] || { echo "$0 Parameter missing: MAPPERS"; exit 1; }
 [ -n "$4" ] || { echo "$0 Parameter missing: REDUCERS"; exit 1; }
 [ -n "$5" ] || { echo "$0 Parameter missing: BASE"; exit 1; }
-[ -n "$6" ] || { echo "$0 Parameter missing: FOLLOW"; exit 1; }
-[ -n "$7" ] || { echo "$0 Parameter missing: NOFOLLOW"; exit 1; }
+#[ -n "$6" ] || { echo "$0 Parameter missing: FOLLOW"; exit 1; }
+#[ -n "$7" ] || { echo "$0 Parameter missing: NOFOLLOW"; exit 1; }
 
 WORKERS="$1"
 SPLITTERS="$2"
@@ -20,7 +20,7 @@ BASE="$5"
 FOLLOW="$6"
 NOFOLLOW="$7"
 
-echo "Doing run: $WORKERS / $SPLITTERS / $MAPPERS / $FIRSTSPLIT / $SPLIT"
+echo "Doing run: $WORKERS / $SPLITTERS / $MAPPERS / $REDUCERS"
 # Start MR sytem and wait a sec
 $MR_BIN start && sleep 1
 
@@ -33,7 +33,7 @@ while [ `cat /tmp/master.state|wc -l` -ne $WORKERS ]; do echo "Waiting for worke
 sleep 2
 
 # make a new dir for curretn constelation
-FILENAME_PREFIX="${WORKERS}_${SPLITTERS}_${MAPPERS}_${FIRSTSPLIT}_${SPLIT}"
+FILENAME_PREFIX="${WORKERS}_${SPLITTERS}_${MAPPERS}_${REDUCERS}"
 mkdir "data_$FILENAME_PREFIX" || { echo "dir exist do not overwrite it: exit"; exit 1; }
 cd "data_$FILENAME_PREFIX"
 
