The scripts folder now contains every script needed to run a test

diff --git a/mapreduce/Examples2/Count/Count_1/scripts/runtest2 b/mapreduce/Examples2/Count/Count_1/scripts/runtest2
--- a/mapreduce/Examples2/Count/Count_1/scripts/runtest2
+++ b/mapreduce/Examples2/Count/Count_1/scripts/runtest2
@@ -1,6 +1,16 @@
 #!/bin/bash
 
-CLIENT="/home/re/holumbus/mapreduce/Examples2/CountWithSimpleIO/Client"
+[ -n "$MR_BIN" ] || { echo "Undefined variable: MR_BIN"; exit 1; }
+[ -n "$START_WORKER_SCRIPT" ] || { echo "Undefined variable: START_WORKER_SCRIPT"; exit 1; }
+[ -n "$CLIENT" ] || { echo "Undefined variable: CLIENT"; exit 1; }
+[ -n "$COPY_WORKER_DATA" ] || { echo "Undefined variable: COPY_WORKER_DATA"; exit 1; }
+[ -n "$1" ] || { echo "Parameter missing: WORKERS"; exit 1; }
+[ -n "$2" ] || { echo "Parameter missing: SPLITTERS"; exit 1; }
+[ -n "$3" ] || { echo "Parameter missing: MAPPERS"; exit 1; }
+[ -n "$4" ] || { echo "Parameter missing: REDUCERS"; exit 1; }
+[ -n "$5" ] || { echo "Parameter missing: FILENAME"; exit 1; }
+[ -n "$6" ] || { echo "Parameter missing: WORDS"; exit 1; }
+
 WORKERS="$1"
 SPLITTERS="$2"
 MAPPERS="$3"
@@ -10,10 +20,10 @@ WORDS="$6"
 
 echo "Doing run: $WORKERS / $SPLITTERS / $MAPPERS / $REDUCERS"
 # Start MR sytem and wait a sec
-/etc/init.d/MR start && sleep 1
+$MR_BIN start && sleep 1
 
 # Start I workers
-startworkercount2 1 $WORKERS
+$START_WORKER_SCRIPT start 1 $WORKERS
 
 # Wait for workers to be started
 while [ `cat /tmp/master.state|wc -l` -ne $WORKERS ]; do echo "Waiting for workers to be started" && sleep 1; done
@@ -29,27 +39,17 @@ cd "data_$FILENAME_PREFIX"
 /usr/bin/time -o "time.txt" -v "$CLIENT" "$FILENAME" "($SPLITTERS,$MAPPERS,$REDUCERS)" "$WORDS" +RTS -N3 -K4G -s"Memory.txt"
 
 # stop workers
-stopworkercount2 1 $WORKERS
+$START_WORKER_SCRIPT stop 1 $WORKERS
 
 # copy workers memory data to here
 sleep 2
 mkdir workerdata
 cd workerdata
-for I in `seq 1 $WORKERS`
-do
-  [ $I -eq 25 ] && continue
-  [ $I -eq 24 ] && continue
-  [ $I -eq 23 ] && continue
-  [ $I -eq 15 ] && I=24
-  [ $I -eq 19 ] && I=23
-  mkdir "worker_$I"
-  cd "worker_$I"
-  scp -r root@172.16.3.$I:/tmp/worker/* . > /dev/null
-  cd ..
-done
+$COPY_WORKER_DATA 1 $WORKERS
+cd .. 
 
-# leave curren tdir
+# leave current dir
 cd ..
 
 # stop mr system and wait a sec
-/etc/init.d/MR stop && sleep 1
+$MR_BIN stop && sleep 1
